language: ruby
before_script: "bundle exec rake appraisal:install"
script: "bundle exec rake appraisal spec"
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  #- jruby-18mode
  #- jruby-19mode
matrix:
  allow_failures:
    - rvm:
      - rbx-18mode
      - rbx-19mode
notifications:
  recipients:
    - josh.martin@wildfireapp.com
    - wael.nasreddine@wildfireapp.com
